### PR TITLE
My Access UI Revisions

### LINKED ISSUE #200: UI changes - My Access
Convert My Access UX to new UI

### PR DESCRIPTION
**Pull request by Jonesy**
Fixes #200 Implements new My Access request flow from UX redesigns.

Preview URL https://api-services-portal-feature-my-access.apps.silver.devops.gov.bc.ca/

Authenticated Test without an application story
1. Visit [API Gateway Services Product](https://api-services-portal-feature-my-access.apps.silver.devops.gov.bc.ca/devportal/api-directory/61a553e072701600189f1341)
2. Sign in
2. Click `Request Access` button
3. There should be no applications on first session. 
4. Click `Create Application` and fill in the revealed fields
5. Select an API environment
6. Add any required comments and select the terms and conditions checkbox
7. Press `Request Access`
8. Any return visits should have the newly created application available in the dropdown

**Auto-Approved Story (Scenario 1)**
1. If is auto approved, collect secrets in the following tab by clicking `Generate Secrets`
2. Click `Done`
3. On the My Access page will see the Approved record with no Collect Credentials

**Auto-Approved Story - Collect Creds Later (Scenario 2)**
1. If is auto approved, click `Done` on the Generate Secrets tab
2. On the My Access page will see the Queued record; click the `Collect Credentials` and then `Generate Credentials` and `Done`
3. On the My Access page will see the Approved record with no Collect Credentials

**Manual Approval Story (Scenario 3)**
1. If not auto approved, collect secrets in the following tab by clicking `Generate Secrets`
2. Click `Done`
3. Display "Pending Approval - Your request for access has been submitted. If approved, your credentials will be authorized to access the API"
4. On the My Access page will see the Pending record with no Collect Credentials button
5. Wait for the status to change from Pending to Approved

**Manual Approval Story - Collect Creds Later (Scenario 4)**
1. If not auto approved, click `Done` on the Generate Secrets tab
2. On the My Access page will see the Queued record; click the `Collect Credentials` and then `Generate Credentials`
3. Click `Done`
3. Display "Pending Approval - Your request for access has been submitted. If approved, your credentials will be authorized to access the API"
4. On the My Access page will see the Pending record with no Collect Credentials button
5. Wait for the status to change from Pending to Approved

Unauthenticated Test
1. Visit [API Gateway Services Product](https://api-services-portal-feature-my-access.apps.silver.devops.gov.bc.ca/devportal/api-directory/61a553e072701600189f1341) not logged in
2. The `Request Access` button should be disabled with text instructions to log in

No Access Requests Story
1. Visit [My Access](https://api-services-portal-feature-my-access.apps.silver.devops.gov.bc.ca/devportal/access)
2. There should be a message prompting the user to visit the API Directory

### CODE REVIEW

**Comment by Jonesy** [comment]
Screen Shot 2021-10-12 at 14 10 00
Screen Shot 2021-10-12 at 14 10 07
Screen Shot 2021-10-12 at 14 10 09
Screen Shot 2021-10-12 at 14 10 19

**Comment by ikethecoder** [comment]
I think some spacing adjustments need to be done here
Screen Shot 2022-01-28 at 5 30 18 PM
.

**Comment by ikethecoder** [comment]
The blue highlight border is getting chopped.
Screen Shot 2022-01-28 at 5 33 52 PM

**Comment by ikethecoder** [comment]
On the Request Access - should "Comments" be "Comments (optional)"?  They are only required if there is "additional instructions" provided by the API owner.

**Comment by ikethecoder** [comment]
Getting an error "You do not have access to this resource" when I collect my credentials.. if I close the dialog and then click the "Generate Credentials" again, it worked.

**Comment by ikethecoder** [comment]
After generating credentials, my request disappears from "My Access".

**Comment by ikethecoder** [comment]
Under Applications, my access does not appear
Screen Shot 2022-01-28 at 5 42 23 PM
.

**Comment by ikethecoder** [comment]
No point showing "No Application Selected" if there are no applications to select?

**Comment by elisafw-ux** [comment]
When there are items to select, the placeholder text should be this: 

Screen Shot 2022-01-28 at 9 53 24 PM

When there are no applications, can we do something like this for the empty state?

Screen Shot 2022-01-28 at 10 30 48 PM

**Review by ikethecoder — APPROVED** [review]

**Pull request merged**
